### ISSUE TITLE
浙大的hujinming也正在做类似的事情

### ISSUE THREAD

**Issue by Chrunge** [PKUFlyingPig/pku-cs-self-learning#1]
https://github.com/conanhujinming/comments-for-awesome-courses/tree/master，然后他还创建了一个Ｑ群643874182

**Comment by PKUFlyingPig** [comment]
看到了，他的课程种类也挺全的，你可以参考。我的话可能考虑是做一个整体培养方案式的导学参考，让计算机小白从零开始一步一步利用这些丰富的开源社区的资源成长起来。
