### ISSUE TITLE
thanks a lot

### ISSUE THREAD

**Issue by MichaelLin2020** [PKUFlyingPig/pku-cs-self-learning#12]
多谢大佬，我也是PKU的本科生，虽然我是人文学部，但我喜欢CS，我也很喜欢自学，基本从初一开始就大多是自己自学了，小学的时候是受启蒙，在这些年的学习中，我痛苦的发现我遇到的好课程居然是我哥和我在网上发现的几年前的付费网络课程，在学校没遇到过我认为很好的课程，包括现在在PKU所上过的课程，这真的是一种很不好的体验，上课我觉得没意思，但又很难做到在课上自学自己想学的知识，导致每天都要浪费很多时间，现在回想起来，初二的那段自学时光是真的很开心啊，基本每次都能学到一些有趣的知识，那个时候学到的东西甚至在高中的时候还一直有用，可惜后来学校的安排越来越紧，很少自己的时间，就再也没那种经历了。再次感谢，期末过去之后我就开始学习您所编纂的内容🤗

**Comment by PKUFlyingPig** [comment]
非常高兴这份指南能给您带来帮助，也祝您学业顺利，自学愉快 ～

**Comment by wlxklyh** [comment]
> 多谢大佬，我也是PKU的本科生，虽然我是人文学部，但我喜欢CS，我也很喜欢自学，基本从初一开始就大多是自己自学了，小学的时候是受启蒙，在这些年的学习中，我痛苦的发现我遇到的好课程居然是我哥和我在网上发现的几年前的付费网络课程，在学校没遇到过我认为很好的课程，包括现在在PKU所上过的课程，这真的是一种很不好的体验，上课我觉得没意思，但又很难做到在课上自学自己想学的知识，导致每天都要浪费很多时间，现在回想起来，初二的那段自学时光是真的很开心啊，基本每次都能学到一些有趣的知识，那个时候学到的东西甚至在高中的时候还一直有用，可惜后来学校的安排越来越紧，很少自己的时间，就再也没那种经历了。再次感谢，期末过去之后我就开始学习您所编纂的内容🤗

PKU的大佬都好有想法啊  加油⛽️⛽️⛽️
