### ISSUE TITLE
体系结构部分

### ISSUE THREAD

**Issue by zyHan2077** [PKUFlyingPig/pku-cs-self-learning#16]
来支持下您。顺便，你的repo昨天火了后，今天被老师在体系实习课上批评了一番，说计组部分太浅，怎么连cs152都不加一下云云（手动狗头）

**Comment by zyHan2077** [comment]
留个言就跑hhh

**Comment by PKUFlyingPig** [comment]
cs152的lab没有开源，所以没有加。要深入学习体系的话可以参考“好书推荐”部分的《量化方法》那本书。

**Comment by PKUFlyingPig** [comment]
当然您老师要是开发一套CS152那样的lab是最好了。
