### ISSUE TITLE
Schema -> Scheme

### ISSUE THREAD

**Issue by Light-of-Hers** [PKUFlyingPig/pku-cs-self-learning#8]
https://github.com/PKUFlyingPig/pku-cs-self-learning/blob/f1f35ac83d0b0b647f73423b646541b07f1b8460/docs/index.md?plain=1#L26
SICP里用的应该是Scheme里的MIT Scheme方言

**Comment by PKUFlyingPig** [comment]
已修正，感谢提醒。
